// src/types/planning.enums.ts (exemple)
export enum DefaultBlockType {
    WORK = 'WORK',
    UNAVAILABILITY = 'UNAVAILABILITY',
}

export enum BreakType {
    MEAL = 'MEAL',
    SHORT_REST = 'SHORT_REST',
    TRAINING_INTERNAL = 'TRAINING_INTERNAL',
    MEETING_INTERNAL = 'MEETING_INTERNAL',
    PLANNED_CLOSURE_SLOT = 'PLANNED_CLOSURE_SLOT',
    OTHER = 'OTHER',
}

export enum SlotType {
    EFFECTIVE_WORK = 'EFFECTIVE_WORK',
    ABSENCE_UNJUSTIFIED = 'ABSENCE_UNJUSTIFIED',
    ABSENCE_JUSTIFIED = 'ABSENCE_JUSTIFIED',
    SICK_LEAVE_CERTIFIED = 'SICK_LEAVE_CERTIFIED',
    SICK_LEAVE_UNCERTIFIED = 'SICK_LEAVE_UNCERTIFIED',
    BUSINESS_TRIP = 'BUSINESS_TRIP',
    MEDICAL_APPOINTMENT = 'MEDICAL_APPOINTMENT',
    TRAINING_EXTERNAL = 'TRAINING_EXTERNAL',
    TRAINING_INTERNAL_ADJUSTMENT = 'TRAINING_INTERNAL_ADJUSTMENT',
    MEETING_EXTERNAL = 'MEETING_EXTERNAL',
    MEETING_INTERNAL_ADJUSTMENT = 'MEETING_INTERNAL_ADJUSTMENT',
    MODEL_BREAK_OVERRIDE = 'MODEL_BREAK_OVERRIDE',
    MANUAL_BREAK = 'MANUAL_BREAK',
    PLANNED_REST_DAY = 'PLANNED_REST_DAY',
    ON_CALL_DUTY = 'ON_CALL_DUTY',
    OTHER_UNAVAILABILITY_MANUAL = 'OTHER_UNAVAILABILITY_MANUAL',
    LATE_ARRIVAL = 'LATE_ARRIVAL',
    EARLY_DEPARTURE = 'EARLY_DEPARTURE',
}